sudo: false
language: python
python:
  - "3.5"
install: pip install tox-travis
script: tox -e travis
before_deploy:
  script: apt-get install pandoc
deploy:
  provider: pypi
  user: "$PYPI_USERNAME"
  password: "$PYPI_PASSWORD"
  on:
    branch: master